site_name: My Docs


docs_dir: site
site_dir: docs

theme:
  name: material

plugins:
  - search
  - tags
  - macros

nav:
  - Главная: index.md
  - Навыки: skills.md
  - FAQ: faq.md
  - Проекты: project.md

extra:
  nothing: "Здесь ничего нет. ПОка что."